-- Insert room test data
INSERT INTO ROOM (ID, BUILDING, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (hibernate_sequence.nextval, 'A', '1', 45, TRUE);
INSERT INTO ROOM (ID, BUILDING, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (hibernate_sequence.nextval, 'A', '2', 40, TRUE);
INSERT INTO ROOM (ID, BUILDING, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (hibernate_sequence.nextval, 'B', '1', 15, TRUE);
INSERT INTO ROOM (ID, BUILDING, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (hibernate_sequence.nextval, 'B', '2', 30, TRUE);
INSERT INTO ROOM (ID, BUILDING, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (hibernate_sequence.nextval, 'H', '2', 10, FALSE);
